degrees: 10.0
fliplr: 0.5
flipud: 0.0
hsv_h: 0.015
hsv_s: 0.4
hsv_v: 0.4
imgsz: 224
lr0: 0.01
lrf: 0.01
mixup: 0.0
momentum: 0.937
mosaic: 0.0
perspective: 0.0
scale: 0.9
shear: 0.0
translate: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
